name=Simple-AstroTracker-Arduino
version=0.7.2
author=NachtRaveVL <nachtravevl@gmail.com>
maintainer=NachtRaveVL <nachtravevl@gmail.com>
sentence=Astruino: Simple automation controller for DIY astronomical tracking systems.
paragraph=Controls hobbyist telescope mounts, covers, cameras, heaters, coolers, fans, sensors, logging, publishing, and night scheduling with offline-first celestial tracking and a built-in target catalog.
category=Other
url=https://github.com/NachtRaveVL/Simple-AstroTracker-Arduino
architectures=*
depends=Adafruit BusIO,Adafruit FT6206 Library,Adafruit GFX Library,Adafruit GPS Library,Adafruit ILI9341,Adafruit ST7735 and ST7789 Library,Adafruit TouchScreen,Adafruit Unified Sensor,ArduinoJson,ArxContainer,ArxSmartPtr,DHT sensor library,I2C_EEPROM,IoAbstraction,LiquidCrystalIO,MQTT,OneWire,RTClib,SimpleCollections,SD,TaskManagerIO,tcUnicodeHelper,tcMenu,TFT_eSPI,Time,U8g2,WiFiEspAT,WiFiNINA_Generic,WiFi101,XPT2046_Touchscreen
includes=Astruino.h
