/*  Astruino: Simple automation controller for DIY astronomical tracking systems.
    Copyright (C) 2026 NachtRaveVL
    Astruino Strings
*/

#ifndef AstroStrings_H
#define AstroStrings_H

#include "Astruino.h"

// Library String Enumeration
// Identifies common library strings that are stored in program Flash when built-in data is enabled.
enum Astro_String : uint16_t {
    // Common strings
    AStr_ColonSpace,                             // ": "
    AStr_DoubleSpace,                            // "  "
    AStr_csv,                                    // "csv"
    AStr_dat,                                    // "dat"
    AStr_Disabled,                               // "Disabled"
    AStr_txt,                                    // "txt"
    AStr_Undefined,                              // "Undefined"
    AStr_null,                                   // "null"

    // Defaults
    AStr_Default_SystemName,                     // "Astruino"
    AStr_Default_ConfigFilename,                 // "Astruino.cfg"

    // Errors
    AStr_Err_AllocationFailure,                  // "Allocation failure"
    AStr_Err_AlreadyInitialized,                 // "Already initialized"
    AStr_Err_AssertionFailure,                   // "Assertion failure: "
    AStr_Err_DataVersionMismatch,                // "Data version mismatch"
    AStr_Err_ExportFailure,                      // "Export failure"
    AStr_Err_HashingCollision,                   // "Hashing collision"
    AStr_Err_ImportFailure,                      // "Import failure"
    AStr_Err_InitializationFailure,              // "Initialization failure"
    AStr_Err_InvalidParameter,                   // "Invalid parameter"
    AStr_Err_InvalidPinOrType,                   // "Invalid pin or type"
    AStr_Err_MeasurementFailure,                 // "Measurement failure"
    AStr_Err_MissingLinkage,                     // "Missing or no linkage"
    AStr_Err_NoPositionsAvailable,               // "No positions available"
    AStr_Err_NotConfiguredProperly,              // "Not configured properly"
    AStr_Err_NotYetInitialized,                  // "Not yet initialized"
    AStr_Err_OperationFailure,                   // "Operation failure"
    AStr_Err_RTCDefaultAddressOnly,              // "RTClib only supports the default I2C RTC address"
    AStr_Err_UnknownDataDecode,                  // "Unknown data decode"
    AStr_Err_UnsupportedOperation,               // "Unsupported operation"

    // Logs
    AStr_Log_AcquireSequence,                    // " acquire sequence"
    AStr_Log_CoverClosing,                       // "Cover closing"
    AStr_Log_CoverOpening,                       // "Cover opening"
    AStr_Log_DaytimeSequence,                    // " daytime sequence"
    AStr_Log_DeploySequence,                     // " deploy sequence"
    AStr_Log_EnvReport,                          // " environment report:"
    AStr_Log_HasBegan,                           // " has began"
    AStr_Log_HasDisabled,                        // " has disabled"
    AStr_Log_HasEnabled,                         // " has enabled"
    AStr_Log_HasEnded,                           // " has ended"
    AStr_Log_ObservationStarted,                 // "Observation started"
    AStr_Log_ObservationStopped,                 // "Observation stopped"
    AStr_Log_PreDuskWarmup,                      // " pre-dusk warm-up"
    AStr_Log_RTCBatteryFailure,                  // "RTC battery failure"
    AStr_Log_StormingSequence,                   // " storming sequence"
    AStr_Log_StowSequence,                       // " stow sequence"
    AStr_Log_SystemDataSaved,                    // "System data saved"
    AStr_Log_SystemUptime,                       // "System uptime: "
    AStr_Log_TrackingSequence,                   // " tracking sequence"

    // Log prefixes
    AStr_Log_Prefix_Info,                        // "[INFO] "
    AStr_Log_Prefix_Warning,                     // "[WARN] "
    AStr_Log_Prefix_Error,                       // "[ERROR] "

    // Log fields
    AStr_Log_Field_Heating_Duration,             // "  Heater run time: "
    AStr_Log_Field_Light_Duration,               // "  Tracking hours: "
    AStr_Log_Field_Temp_Measured,                // "  Temperature: "
    AStr_Log_Field_Time_Finish,                  // "  Finish time: "
    AStr_Log_Field_Time_Measured,                // "  Elapsed time: "
    AStr_Log_Field_Time_Start,                   // "  Start time: "
    AStr_Log_Field_WindSpeed_Measured,           // "  Wind speed: "

    // JSON / data keys
    AStr_Key_ActiveLow,                          // "activeLow"
    AStr_Key_AutosaveEnabled,                    // "autosaveEnabled"
    AStr_Key_AutosaveFallback,                   // "autosaveFallback"
    AStr_Key_AutosaveInterval,                   // "autosaveInterval"
    AStr_Key_BitRes,                             // "bitRes"
    AStr_Key_CalibrationUnits,                   // "calibrationUnits"
    AStr_Key_CatalogId,                          // "catalogId"
    AStr_Key_Channel,                            // "channel"
    AStr_Key_ContinuousPowerUsage,               // "continuousPowerUsage"
    AStr_Key_CtrlInMode,                         // "ctrlInMode"
    AStr_Key_DataFilePrefix,                     // "dataFilePrefix"
    AStr_Key_DeclinationArcseconds,              // "declinationArcseconds"
    AStr_Key_DetriggerDelay,                     // "detriggerDelay"
    AStr_Key_DetriggerTol,                       // "detriggerTol"
    AStr_Key_DisplayTheme,                       // "displayTheme"
    AStr_Key_DispOutMode,                        // "dispOutMode"
    AStr_Key_EnableMode,                         // "enableMode"
    AStr_Key_Id,                                 // "id"
    AStr_Key_InputPin,                           // "inputPin"
    AStr_Key_JoystickCalib,                      // "joystickCalib"
    AStr_Key_LimitTrigger,                       // "limitTrigger"
    AStr_Key_Location,                           // "location"
    AStr_Key_LogFilePrefix,                      // "logFilePrefix"
    AStr_Key_Logger,                             // "logger"
    AStr_Key_LogLevel,                           // "logLevel"
    AStr_Key_LogToSDCard,                        // "logToSDCard"
    AStr_Key_LogToWiFiStorage,                   // "logToWiFiStorage"
    AStr_Key_MACAddress,                         // "macAddress"
    AStr_Key_MaxActiveAtOnce,                    // "maxActiveAtOnce"
    AStr_Key_MaxContinuousMs,                    // "maxContinuousMs"
    AStr_Key_MaximumPosition,                    // "maximumPosition"
    AStr_Key_MaxPower,                           // "maxPower"
    AStr_Key_MeasurementRow,                     // "measurementRow"
    AStr_Key_MeasurementUnits,                   // "measurementUnits"
    AStr_Key_MeasureMode,                        // "measureMode"
    AStr_Key_MinimumPosition,                    // "minimumPosition"
    AStr_Key_Mode,                               // "mode"
    AStr_Key_MovingTarget,                       // "movingTarget"
    AStr_Key_Multiplier,                         // "multiplier"
    AStr_Key_Offset,                             // "offset"
    AStr_Key_OutputPin,                          // "outputPin"
    AStr_Key_OutputPin2,                         // "outputPin2"
    AStr_Key_ParkPrimary,                        // "parkPrimary"
    AStr_Key_ParkSecondary,                      // "parkSecondary"
    AStr_Key_Pin,                                // "pin"
    AStr_Key_PollingInterval,                    // "pollingInterval"
    AStr_Key_PowerUnits,                         // "powerUnits"
    AStr_Key_PowerUsageSensor,                   // "powerUsageSensor"
    AStr_Key_PreDuskHeatingMins,                 // "preDuskHeatingMins"
    AStr_Key_PrimaryAxisRate,                    // "primaryAxisRate"
    AStr_Key_PrimaryLimitsEnabled,               // "primaryLimitsEnabled"
    AStr_Key_PrimaryMaximum,                     // "primaryMaximum"
    AStr_Key_PrimaryMinimum,                     // "primaryMinimum"
    AStr_Key_Publisher,                          // "publisher"
    AStr_Key_PublishToSDCard,                    // "pubToSDCard"
    AStr_Key_PublishToWiFiStorage,               // "pubToWiFiStorage"
    AStr_Key_PWMChannel,                         // "pwmChannel"
    AStr_Key_PWMFrequency,                       // "pwmFrequency"
    AStr_Key_RailName,                           // "railName"
    AStr_Key_ReportInterval,                     // "reportInterval"
    AStr_Key_Revision,                           // "revision"
    AStr_Key_RightAscensionSeconds,              // "rightAscensionSeconds"
    AStr_Key_Scheduler,                          // "scheduler"
    AStr_Key_SecondaryAxisRate,                  // "secondaryAxisRate"
    AStr_Key_SecondaryLimitsEnabled,             // "secondaryLimitsEnabled"
    AStr_Key_SecondaryMaximum,                   // "secondaryMaximum"
    AStr_Key_SecondaryMinimum,                   // "secondaryMinimum"
    AStr_Key_SensorName,                         // "sensorName"
    AStr_Key_StateStableTimeMs,                  // "stateStableTimeMs"
    AStr_Key_SystemMode,                         // "systemMode"
    AStr_Key_SystemName,                         // "systemName"
    AStr_Key_TargetClass,                        // "targetClass"
    AStr_Key_TargetName,                         // "targetName"
    AStr_Key_TargetType,                         // "targetType"
    AStr_Key_Timestamp,                          // "timestamp"
    AStr_Key_TimeZoneOffset,                     // "timeZoneOffset"
    AStr_Key_Tolerance,                          // "tolerance"
    AStr_Key_ToleranceHigh,                      // "toleranceHigh"
    AStr_Key_ToleranceLow,                       // "toleranceLow"
    AStr_Key_TriggerBelow,                       // "triggerBelow"
    AStr_Key_TriggerOutside,                     // "triggerOutside"
    AStr_Key_Type,                               // "type"
    AStr_Key_Units,                              // "units"
    AStr_Key_UpdatesPerSec,                      // "updatesPerSec"
    AStr_Key_UsingISR,                           // "usingISR"
    AStr_Key_Value,                              // "value"
    AStr_Key_Version,                            // "version"
    AStr_Key_WiFiPassword,                       // "wifiPassword"
    AStr_Key_WiFiPasswordSeed,                   // "wifiPasswordSeed"
    AStr_Key_WiFiSSID,                           // "wifiSSID"

    // Object strings
    AStr_Actuator,                               // "Actuator"
    AStr_Mount,                                  // "Mount"
    AStr_ObservationDevice,                      // "ObservationDevice"
    AStr_ObservationDeviceDisplay,               // "Observation Device"
    AStr_Rail,                                   // "Rail"
    AStr_Sensor,                                 // "Sensor"
    AStr_Target,                                 // "Target"

    // Enum strings
    AStr_Enum_AC110V,                            // "AC110V"
    AStr_Enum_AC220V,                            // "AC220V"
    AStr_Enum_Achernar,                          // "Achernar"
    AStr_Enum_Acquire,                           // "Acquire"
    AStr_Enum_Acrux,                             // "Acrux"
    AStr_Enum_Aldebaran,                         // "Aldebaran"
    AStr_Enum_Alnilam,                           // "Alnilam"
    AStr_Enum_Alnitak,                           // "Alnitak"
    AStr_Enum_Altair,                            // "Altair"
    AStr_Enum_AltAzimuth,                        // "AltAzimuth"
    AStr_Enum_AnalogInput,                       // "AnalogInput"
    AStr_Enum_AnalogJoystick,                    // "AnalogJoystick"
    AStr_Enum_AnalogOutput,                      // "AnalogOutput"
    AStr_Enum_Angle,                             // "Angle"
    AStr_Enum_Antares,                           // "Antares"
    AStr_Enum_Arcturus,                          // "Arcturus"
    AStr_Enum_AscOrder,                          // "AscOrder"
    AStr_Enum_Average,                           // "Average"
    AStr_Enum_Balancing,                         // "Balancing"
    AStr_Enum_Bellatrix,                         // "Bellatrix"
    AStr_Enum_Betelgeuse,                        // "Betelgeuse"
    AStr_Enum_CameraCooler,                      // "CameraCooler"
    AStr_Enum_CameraTemperature,                 // "CameraTemperature"
    AStr_Enum_Canopus,                           // "Canopus"
    AStr_Enum_Capella,                           // "Capella"
    AStr_Enum_Castor,                            // "Castor"
    AStr_Enum_Count,                             // "Count"
    AStr_Enum_Cover,                             // "Cover"
    AStr_Enum_Current,                           // "Current"
    AStr_Enum_CustomOLED,                        // "CustomOLED"
    AStr_Enum_CustomTarget1,                     // "CustomTarget1"
    AStr_Enum_CustomTarget2,                     // "CustomTarget2"
    AStr_Enum_CustomTarget3,                     // "CustomTarget3"
    AStr_Enum_CustomTarget4,                     // "CustomTarget4"
    AStr_Enum_CustomTarget5,                     // "CustomTarget5"
    AStr_Enum_CustomTarget6,                     // "CustomTarget6"
    AStr_Enum_CustomTarget7,                     // "CustomTarget7"
    AStr_Enum_CustomTarget8,                     // "CustomTarget8"
    AStr_Enum_DayStorage,                        // "DayStorage"
    AStr_Enum_DC12V,                             // "DC12V"
    AStr_Enum_DC24V,                             // "DC24V"
    AStr_Enum_DC3V3,                             // "DC3V3"
    AStr_Enum_DC48V,                             // "DC48V"
    AStr_Enum_DC5V,                              // "DC5V"
    AStr_Enum_Deneb,                             // "Deneb"
    AStr_Enum_Deploy,                            // "Deploy"
    AStr_Enum_DescOrder,                         // "DescOrder"
    AStr_Enum_DewHeater,                         // "DewHeater"
    AStr_Enum_DigitalInput,                      // "DigitalInput"
    AStr_Enum_DigitalInputPullDown,              // "DigitalInputPullDown"
    AStr_Enum_DigitalInputPullUp,                // "DigitalInputPullUp"
    AStr_Enum_DigitalOutput,                     // "DigitalOutput"
    AStr_Enum_DigitalOutputPushPull,             // "DigitalOutputPushPull"
    AStr_Enum_Distance,                          // "Distance"
    AStr_Enum_Dubhe,                             // "Dubhe"
    AStr_Enum_Equatorial,                        // "Equatorial"
    AStr_Enum_Fan,                               // "Fan"
    AStr_Enum_Focuser,                           // "Focuser"
    AStr_Enum_Fomalhaut,                         // "Fomalhaut"
    AStr_Enum_Galaxy,                            // "Galaxy"
    AStr_Enum_GlobularCluster,                   // "GlobularCluster"
    AStr_Enum_Hadar,                             // "Hadar"
    AStr_Enum_Highest,                           // "Highest"
    AStr_Enum_Humidity,                          // "Humidity"
    AStr_Enum_IL3820,                            // "IL3820"
    AStr_Enum_IL3820V2,                          // "IL3820V2"
    AStr_Enum_ILI9341,                           // "ILI9341"
    AStr_Enum_Imperial,                          // "Imperial"
    AStr_Enum_Init,                              // "Init"
    AStr_Enum_InOrder,                           // "InOrder"
    AStr_Enum_Jupiter,                           // "Jupiter"
    AStr_Enum_LCD16x2,                           // "LCD16x2"
    AStr_Enum_LCD20x4,                           // "LCD20x4"
    AStr_Enum_Light,                             // "Light"
    AStr_Enum_LimitSwitch,                       // "LimitSwitch"
    AStr_Enum_Lowest,                            // "Lowest"
    AStr_Enum_M1,                                // "M1"
    AStr_Enum_M2,                                // "M2"
    AStr_Enum_M3,                                // "M3"
    AStr_Enum_M4,                                // "M4"
    AStr_Enum_M5,                                // "M5"
    AStr_Enum_M6,                                // "M6"
    AStr_Enum_M7,                                // "M7"
    AStr_Enum_M8,                                // "M8"
    AStr_Enum_M9,                                // "M9"
    AStr_Enum_M10,                               // "M10"
    AStr_Enum_M11,                               // "M11"
    AStr_Enum_M12,                               // "M12"
    AStr_Enum_M13,                               // "M13"
    AStr_Enum_M14,                               // "M14"
    AStr_Enum_M15,                               // "M15"
    AStr_Enum_M16,                               // "M16"
    AStr_Enum_M17,                               // "M17"
    AStr_Enum_M18,                               // "M18"
    AStr_Enum_M19,                               // "M19"
    AStr_Enum_M20,                               // "M20"
    AStr_Enum_M21,                               // "M21"
    AStr_Enum_M22,                               // "M22"
    AStr_Enum_M23,                               // "M23"
    AStr_Enum_M24,                               // "M24"
    AStr_Enum_M25,                               // "M25"
    AStr_Enum_M26,                               // "M26"
    AStr_Enum_M27,                               // "M27"
    AStr_Enum_M28,                               // "M28"
    AStr_Enum_M29,                               // "M29"
    AStr_Enum_M30,                               // "M30"
    AStr_Enum_M31,                               // "M31"
    AStr_Enum_M32,                               // "M32"
    AStr_Enum_M33,                               // "M33"
    AStr_Enum_M34,                               // "M34"
    AStr_Enum_M35,                               // "M35"
    AStr_Enum_M36,                               // "M36"
    AStr_Enum_M37,                               // "M37"
    AStr_Enum_M38,                               // "M38"
    AStr_Enum_M39,                               // "M39"
    AStr_Enum_M40,                               // "M40"
    AStr_Enum_M41,                               // "M41"
    AStr_Enum_M42,                               // "M42"
    AStr_Enum_M43,                               // "M43"
    AStr_Enum_M44,                               // "M44"
    AStr_Enum_M45,                               // "M45"
    AStr_Enum_M46,                               // "M46"
    AStr_Enum_M47,                               // "M47"
    AStr_Enum_M48,                               // "M48"
    AStr_Enum_M49,                               // "M49"
    AStr_Enum_M50,                               // "M50"
    AStr_Enum_M51,                               // "M51"
    AStr_Enum_M52,                               // "M52"
    AStr_Enum_M53,                               // "M53"
    AStr_Enum_M54,                               // "M54"
    AStr_Enum_M55,                               // "M55"
    AStr_Enum_M56,                               // "M56"
    AStr_Enum_M57,                               // "M57"
    AStr_Enum_M58,                               // "M58"
    AStr_Enum_M59,                               // "M59"
    AStr_Enum_M60,                               // "M60"
    AStr_Enum_M61,                               // "M61"
    AStr_Enum_M62,                               // "M62"
    AStr_Enum_M63,                               // "M63"
    AStr_Enum_M64,                               // "M64"
    AStr_Enum_M65,                               // "M65"
    AStr_Enum_M66,                               // "M66"
    AStr_Enum_M67,                               // "M67"
    AStr_Enum_M68,                               // "M68"
    AStr_Enum_M69,                               // "M69"
    AStr_Enum_M70,                               // "M70"
    AStr_Enum_M71,                               // "M71"
    AStr_Enum_M72,                               // "M72"
    AStr_Enum_M73,                               // "M73"
    AStr_Enum_M74,                               // "M74"
    AStr_Enum_M75,                               // "M75"
    AStr_Enum_M76,                               // "M76"
    AStr_Enum_M77,                               // "M77"
    AStr_Enum_M78,                               // "M78"
    AStr_Enum_M79,                               // "M79"
    AStr_Enum_M80,                               // "M80"
    AStr_Enum_M81,                               // "M81"
    AStr_Enum_M82,                               // "M82"
    AStr_Enum_M83,                               // "M83"
    AStr_Enum_M84,                               // "M84"
    AStr_Enum_M85,                               // "M85"
    AStr_Enum_M86,                               // "M86"
    AStr_Enum_M87,                               // "M87"
    AStr_Enum_M88,                               // "M88"
    AStr_Enum_M89,                               // "M89"
    AStr_Enum_M90,                               // "M90"
    AStr_Enum_M91,                               // "M91"
    AStr_Enum_M92,                               // "M92"
    AStr_Enum_M93,                               // "M93"
    AStr_Enum_M94,                               // "M94"
    AStr_Enum_M95,                               // "M95"
    AStr_Enum_M96,                               // "M96"
    AStr_Enum_M97,                               // "M97"
    AStr_Enum_M98,                               // "M98"
    AStr_Enum_M99,                               // "M99"
    AStr_Enum_M100,                              // "M100"
    AStr_Enum_M101,                              // "M101"
    AStr_Enum_M102,                              // "M102"
    AStr_Enum_M103,                              // "M103"
    AStr_Enum_M104,                              // "M104"
    AStr_Enum_M105,                              // "M105"
    AStr_Enum_M106,                              // "M106"
    AStr_Enum_M107,                              // "M107"
    AStr_Enum_M108,                              // "M108"
    AStr_Enum_M109,                              // "M109"
    AStr_Enum_M110,                              // "M110"
    AStr_Enum_Manual,                            // "Manual"
    AStr_Enum_Mars,                              // "Mars"
    AStr_Enum_Matrix2x2,                         // "Matrix2x2"
    AStr_Enum_Matrix3x4,                         // "Matrix3x4"
    AStr_Enum_Matrix4x4,                         // "Matrix4x4"
    AStr_Enum_Mercury,                           // "Mercury"
    AStr_Enum_Metric,                            // "Metric"
    AStr_Enum_Mizar,                             // "Mizar"
    AStr_Enum_Moon,                              // "Moon"
    AStr_Enum_MountAxis,                         // "MountAxis"
    AStr_Enum_Multiply,                          // "Multiply"
    AStr_Enum_Nebula,                            // "Nebula"
    AStr_Enum_Neptune,                           // "Neptune"
    AStr_Enum_NightObserving,                    // "NightObserving"
    AStr_Enum_OpenCluster,                       // "OpenCluster"
    AStr_Enum_Other,                             // "Other"
    AStr_Enum_Percentile,                        // "Percentile"
    AStr_Enum_PlanetaryNebula,                   // "PlanetaryNebula"
    AStr_Enum_Polaris,                           // "Polaris"
    AStr_Enum_Pollux,                            // "Pollux"
    AStr_Enum_Position,                          // "Position"
    AStr_Enum_Power,                             // "Power"
    AStr_Enum_Procyon,                           // "Procyon"
    AStr_Enum_Rain,                              // "Rain"
    AStr_Enum_Raw,                               // "Raw"
    AStr_Enum_Regulus,                           // "Regulus"
    AStr_Enum_RemoteControl,                     // "RemoteControl"
    AStr_Enum_ResistiveTouch,                    // "ResistiveTouch"
    AStr_Enum_RevOrder,                          // "RevOrder"
    AStr_Enum_RigelKentaurus,                    // "RigelKentaurus"
    AStr_Enum_RotaryEncoder,                     // "RotaryEncoder"
    AStr_Enum_SafeStowed,                        // "SafeStowed"
    AStr_Enum_Saturn,                            // "Saturn"
    AStr_Enum_Scientific,                        // "Scientific"
    AStr_Enum_SH1106,                            // "SH1106"
    AStr_Enum_SingleAxis,                        // "SingleAxis"
    AStr_Enum_Sirius,                            // "Sirius"
    AStr_Enum_SolarSystem,                       // "SolarSystem"
    AStr_Enum_Speed,                             // "Speed"
    AStr_Enum_Spica,                             // "Spica"
    AStr_Enum_SSD1305,                           // "SSD1305"
    AStr_Enum_SSD1305x32Ada,                     // "SSD1305x32Ada"
    AStr_Enum_SSD1305x64Ada,                     // "SSD1305x64Ada"
    AStr_Enum_SSD1306,                           // "SSD1306"
    AStr_Enum_SSD1607,                           // "SSD1607"
    AStr_Enum_ST7735,                            // "ST7735"
    AStr_Enum_ST7789,                            // "ST7789"
    AStr_Enum_Star,                              // "Star"
    AStr_Enum_Stow,                              // "Stow"
    AStr_Enum_Sun,                               // "Sun"
    AStr_Enum_Temperature,                       // "Temperature"
    AStr_Enum_TFTTouch,                          // "TFTTouch"
    AStr_Enum_TouchScreen,                       // "TouchScreen"
    AStr_Enum_Track,                             // "Track"
    AStr_Enum_Tracking,                          // "Tracking"
    AStr_Enum_UpDownButtons,                     // "UpDownButtons"
    AStr_Enum_UpDownESP32Touch,                  // "UpDownESP32Touch"
    AStr_Enum_Uranus,                            // "Uranus"
    AStr_Enum_Vega,                              // "Vega"
    AStr_Enum_Venus,                             // "Venus"
    AStr_Enum_Voltage,                           // "Voltage"
    AStr_Enum_Warm,                              // "Warm"
    AStr_Enum_WindSpeed,                         // "WindSpeed"

    // Unit strings
    AStr_Unit_Count,                             // "Count"
    AStr_Unit_A,                                 // "A"
    AStr_Unit_C,                                 // "C"
    AStr_Unit_deg,                               // "deg"
    AStr_Unit_F,                                 // "F"
    AStr_Unit_ft,                                // "ft"
    AStr_Unit_ftPers,                            // "ft/s"
    AStr_Unit_K,                                 // "K"
    AStr_Unit_m,                                 // "m"
    AStr_Unit_mPers,                             // "m/s"
    AStr_Unit_N1,                                // "1"
    AStr_Unit_Percent,                           // "%"
    AStr_Unit_PercentRH,                         // "%RH"
    AStr_Unit_rad,                               // "rad"
    AStr_Unit_V,                                 // "V"
    AStr_Unit_W,                                 // "W"
    AStr_Unit_Undefined,                         // "Undefined"

    AStr_Count                                   // String count
};

// Blank string pointer used when no Flash string is available.
extern const char *AStr_Blank;

// Returns memory resident string from PROGMEM (Flash), EEPROM, or SD-backed string number.
extern String stringFromPGM(Astro_String strNum);
#define SFP(strNum) stringFromPGM((strNum))

// Returns memory resident string from a PROGMEM (Flash) string address.
extern String stringFromPGMAddr(const char *flashStr);

// Makes string lookup go through EEPROM at the specified data begin address.
extern void beginStringsFromEEPROM(uint16_t dataAddress);

// Makes string lookup go through an SD card strings file at the specified file prefix.
extern void beginStringsFromSDCard(const String &dataFilePrefix);

#ifndef ASTRO_DISABLE_BUILTIN_DATA
// Returns string from given PROGMEM (Flash) string address.
String stringFromPGMAddr(const char *flashStr);

// Returns PROGMEM (Flash) address pointer given string number.
const char *pgmAddrForStr(Astro_String strNum);
#define CFP(strNum) pgmAddrForStr(strNum)
#else
#define CFP(strNum) SFP(strNum).c_str()
#endif

#endif // /ifndef AstroStrings_H
