/*  Astruino: Simple automation controller for DIY astronomical tracking systems.
    Copyright (C) 2026 NachtRaveVL
    Astruino Strings
*/

#ifndef AstroStrings_H
#define AstroStrings_H

#include "Astruino.h"

// Library String Enumeration
// Identifies common library strings that are stored in program Flash when built-in data is enabled.
enum Astro_String : uint16_t {
    // Common strings
    AStr_ColonSpace,                         // ": "
    AStr_Blank2,                             // "  "
    AStr_Space,                              // " "
    AStr_csv,                                // "csv"
    AStr_dat,                                // "dat"
    AStr_txt,                                // "txt"
    AStr_null,                               // "null"
    AStr_Empty,                              // ""
    AStr_public,                             // "public"
    AStr_In,                                 // " in "
    AStr_HARD,                               // " HARD"

    // Defaults
    AStr_Default_SystemName,                 // "Astruino"
    AStr_Default_ConfigFilename,             // "Astruino.cfg"


    // Errors
    AStr_Err_AllocationFailure,                  // "Allocation failure"
    AStr_Err_AlreadyInitialized,                 // "Already initialized"
    AStr_Err_ExportFailure,                      // "Export failure"
    AStr_Err_ImportFailure,                      // "Import failure"
    AStr_Err_InvalidParameter,                   // "Invalid parameter"
    AStr_Err_NotYetInitialized,                  // "Not yet initialized"
    AStr_Err_OperationFailure,                   // "Operation failure"
    AStr_Err_AssertionFailure,               // "Assertion failure: "
    AStr_Err_AssertionFailureHARD,           // "Assertion failure HARD: "
    AStr_Err_DataVersionMismatch,            // "Data version mismatch"
    AStr_Err_HashingCollision,               // "Hashing collision"
    AStr_Err_NotConfiguredProperly,          // "Not configured properly"
    AStr_Err_RTCDefaultAddressOnly,          // "RTClib only supports the default I2C RTC address"
    AStr_Err_UnknownDataDecode,              // "Unknown data decode"
    AStr_Err_UnsupportedOperation,           // "Unsupported operation"

    // Logs
    AStr_Log_SystemUptime,                  // "System uptime: "
    AStr_Log_EnvReport,                  // "Environment report"
    AStr_ObservationStarted,                 // "Observation started"
    AStr_ObservationStopped,                 // "Observation stopped"
    AStr_CoverOpening,                       // "Cover opening"
    AStr_CoverClosing,                       // "Cover closing"
    AStr_Log_SystemDataSaved,                    // "System data saved"
    AStr_Log_RTCBatteryFailure,              // "RTC battery failure"

    // Log prefixes / fields
    AStr_Log_Prefix_Info,                    // "[INFO] "
    AStr_Log_Prefix_Warning,                 // "[WARN] "
    AStr_Log_Prefix_Error,                   // "[ERROR] "

    // JSON / data keys
    AStr_Key_Type,                           // "type"
    AStr_Key_Version,                        // "version"
    AStr_Key_Revision,                       // "revision"
    AStr_Key_Id,                             // "id"
    AStr_Key_SystemMode,                     // "systemMode"
    AStr_Key_MeasureMode,                    // "measureMode"
    AStr_Key_DispOutMode,                    // "dispOutMode"
    AStr_Key_CtrlInMode,                     // "ctrlInMode"
    AStr_Key_SystemName,                     // "systemName"
    AStr_Key_TimeZoneOffset,                 // "timeZoneOffset"
    AStr_Key_PollingInterval,                // "pollingInterval"
    AStr_Key_AutosaveEnabled,                // "autosaveEnabled"
    AStr_Key_AutosaveFallback,               // "autosaveFallback"
    AStr_Key_AutosaveInterval,               // "autosaveInterval"
    AStr_Key_WiFiSSID,                       // "wifiSSID"
    AStr_Key_WiFiPassword,                   // "wifiPassword"
    AStr_Key_WiFiPasswordSeed,               // "wifiPasswordSeed"
    AStr_Key_MACAddress,                     // "macAddress"
    AStr_Key_Location,                       // "location"
    AStr_Key_Scheduler,                      // "scheduler"
    AStr_Key_Logger,                         // "logger"
    AStr_Key_Publisher,                      // "publisher"
    AStr_Key_SensorName,                     // "sensorName"
    AStr_Key_CalibrationUnits,               // "calibrationUnits"
    AStr_Key_Multiplier,                     // "multiplier"
    AStr_Key_Offset,                         // "offset"
    AStr_Key_MeasurementRow,                 // "measurementRow"
    AStr_Key_MeasurementUnits,               // "measurementUnits"
    AStr_Key_Value,                          // "value"
    AStr_Key_Units,                          // "units"
    AStr_Key_Timestamp,                      // "timestamp"
    AStr_Key_InputPin,                       // "inputPin"
    AStr_Key_OutputPin,                      // "outputPin"
    AStr_Key_OutputPin2,                     // "outputPin2"
    AStr_Key_EnableMode,                     // "enableMode"
    AStr_Key_ContinuousPowerUsage,           // "continuousPowerUsage"
    AStr_Key_RailName,                       // "railName"
    AStr_Key_MinimumPosition,                // "minimumPosition"
    AStr_Key_MaximumPosition,                // "maximumPosition"
    AStr_Key_MaxContinuousMs,                // "maxContinuousMs"
    AStr_Key_DetriggerTol,                   // "detriggerTol"
    AStr_Key_DetriggerDelay,                 // "detriggerDelay"
    AStr_Key_Tolerance,                      // "tolerance"
    AStr_Key_TriggerBelow,                   // "triggerBelow"
    AStr_Key_ToleranceLow,                   // "toleranceLow"
    AStr_Key_ToleranceHigh,                  // "toleranceHigh"
    AStr_Key_TriggerOutside,                 // "triggerOutside"
    AStr_Key_Pin,                            // "pin"
    AStr_Key_Mode,                           // "mode"
    AStr_Key_Channel,                        // "channel"
    AStr_Key_ActiveLow,                      // "activeLow"
    AStr_Key_BitRes,                         // "bitRes"
    AStr_Key_PWMChannel,                     // "pwmChannel"
    AStr_Key_PWMFrequency,                   // "pwmFrequency"
    AStr_Key_LogLevel,                       // "logLevel"
    AStr_Key_LogFilePrefix,                  // "logFilePrefix"
    AStr_Key_LogToSDCard,                    // "logToSDCard"
    AStr_Key_LogToWiFiStorage,               // "logToWiFiStorage"
    AStr_Key_DataFilePrefix,                 // "dataFilePrefix"
    AStr_Key_PublishToSDCard,                // "pubToSDCard"
    AStr_Key_PublishToWiFiStorage,           // "pubToWiFiStorage"
    AStr_Key_PowerUnits,                     // "powerUnits"
    AStr_Key_MaxActiveAtOnce,                // "maxActiveAtOnce"
    AStr_Key_MaxPower,                       // "maxPower"
    AStr_Key_PowerUsageSensor,               // "powerUsageSensor"
    AStr_Key_LimitTrigger,                   // "limitTrigger"
    AStr_Key_CatalogId,                      // "catalogId"
    AStr_Key_TargetName,                     // "targetName"
    AStr_Key_TargetClass,                    // "targetClass"
    AStr_Key_RightAscensionSeconds,          // "rightAscensionSeconds"
    AStr_Key_DeclinationArcseconds,          // "declinationArcseconds"
    AStr_Key_MovingTarget,                   // "movingTarget"
    AStr_Key_TargetType,                     // "targetType"
    AStr_Key_PrimaryAxisRate,                // "primaryAxisRate"
    AStr_Key_SecondaryAxisRate,              // "secondaryAxisRate"
    AStr_Key_ParkPrimary,                    // "parkPrimary"
    AStr_Key_ParkSecondary,                  // "parkSecondary"
    AStr_Key_PrimaryMinimum,                 // "primaryMinimum"
    AStr_Key_PrimaryMaximum,                 // "primaryMaximum"
    AStr_Key_PrimaryLimitsEnabled,           // "primaryLimitsEnabled"
    AStr_Key_SecondaryMinimum,               // "secondaryMinimum"
    AStr_Key_SecondaryMaximum,               // "secondaryMaximum"
    AStr_Key_SecondaryLimitsEnabled,         // "secondaryLimitsEnabled"
    AStr_Key_DeploySunAlt,                   // "deploySunAlt"
    AStr_Key_StowSunAlt,                     // "stowSunAlt"
    AStr_Key_AlignTol,                       // "alignTol"
    AStr_Key_SettleSecs,                     // "settleSecs"
    AStr_Key_ReportSecs,                     // "reportSecs"

    // Enum / domain strings
    AStr_Actuator,                           // "Actuator"
    AStr_Sensor,                             // "Sensor"
    AStr_Target,                             // "Target"
    AStr_Mount,                              // "Mount"
    AStr_Rail,                               // "Rail"
    AStr_ObservationDevice,                  // "ObservationDevice"
    AStr_ObservationDeviceDisplay,           // "Observation Device"
    AStr_Unknown,                            // "Unknown"
    AStr_Tracking,                           // "Tracking"
    AStr_Balancing,                          // "Balancing"
    AStr_Manual,                             // "Manual"
    AStr_Enum_Count,                         // "Count"
    AStr_Undefined,                          // "Undefined"
    AStr_Imperial,                           // "Imperial"
    AStr_Metric,                             // "Metric"
    AStr_Scientific,                         // "Scientific"
    AStr_MountAxis,                          // "MountAxis"
    AStr_Cover,                              // "Cover"
    AStr_DewHeater,                          // "DewHeater"
    AStr_CameraCooler,                       // "CameraCooler"
    AStr_Fan,                                // "Fan"
    AStr_Focuser,                            // "Focuser"
    AStr_Generic,                            // "Generic"
    AStr_Temperature,                        // "Temperature"
    AStr_Humidity,                           // "Humidity"
    AStr_Position,                           // "Position"
    AStr_LimitSwitch,                        // "LimitSwitch"
    AStr_Rain,                               // "Rain"
    AStr_WindSpeed,                          // "WindSpeed"
    AStr_Light,                              // "Light"
    AStr_Voltage,                            // "Voltage"
    AStr_Current,                            // "Current"
    AStr_CameraTemperature,                  // "CameraTemperature"
    AStr_Equatorial,                         // "Equatorial"
    AStr_AltAzimuth,                         // "AltAzimuth"
    AStr_SingleAxis,                         // "SingleAxis"
    AStr_DC3V3,                              // "DC3V3"
    AStr_DC5V,                               // "DC5V"
    AStr_DC12V,                              // "DC12V"
    AStr_DC24V,                              // "DC24V"
    AStr_DigitalInput,                       // "DigitalInput"
    AStr_DigitalInputPullUp,                 // "DigitalInputPullUp"
    AStr_DigitalInputPullDown,               // "DigitalInputPullDown"
    AStr_DigitalOutput,                      // "DigitalOutput"
    AStr_DigitalOutputPushPull,              // "DigitalOutputPushPull"
    AStr_AnalogInput,                        // "AnalogInput"
    AStr_AnalogOutput,                       // "AnalogOutput"
    AStr_Highest,                            // "Highest"
    AStr_Lowest,                             // "Lowest"
    AStr_Average,                            // "Average"
    AStr_Multiply,                           // "Multiply"
    AStr_InOrder,                            // "InOrder"
    AStr_RevOrder,                           // "RevOrder"
    AStr_Raw,                                // "Raw"
    AStr_Angle,                              // "Angle"
    AStr_Distance,                           // "Distance"
    AStr_Percentile,                         // "Percentile"
    AStr_Speed,                              // "Speed"
    AStr_Power,                              // "Power"
    AStr_Star,                               // "Star"
    AStr_OpenCluster,                        // "OpenCluster"
    AStr_GlobularCluster,                    // "GlobularCluster"
    AStr_Nebula,                             // "Nebula"
    AStr_PlanetaryNebula,                    // "PlanetaryNebula"
    AStr_Galaxy,                             // "Galaxy"
    AStr_SolarSystem,                        // "SolarSystem"
    AStr_Other,                              // "Other"
    AStr_DayStorage,                         // "DayStorage"
    AStr_NightObserving,                     // "NightObserving"
    AStr_SafeStowed,                         // "SafeStowed"
    AStr_DayStowed,                          // "DayStowed"
    AStr_Deploying,                          // "Deploying"
    AStr_Cooling,                            // "Cooling"
    AStr_Slewing,                            // "Slewing"
    AStr_Settling,                           // "Settling"
    AStr_Observing,                          // "Observing"
    AStr_Warming,                            // "Warming"
    AStr_Stowing,                            // "Stowing"
    AStr_Fault,                              // "Fault"
    AStr_Sun,                                // "Sun"
    AStr_Moon,                               // "Moon"
    AStr_Mercury,                            // "Mercury"
    AStr_Venus,                              // "Venus"
    AStr_Mars,                               // "Mars"
    AStr_Jupiter,                            // "Jupiter"
    AStr_Saturn,                             // "Saturn"
    AStr_Uranus,                             // "Uranus"
    AStr_Neptune,                            // "Neptune"
    AStr_Sirius,                             // "Sirius"
    AStr_Canopus,                            // "Canopus"
    AStr_Arcturus,                           // "Arcturus"
    AStr_Vega,                               // "Vega"
    AStr_Capella,                            // "Capella"
    AStr_RigelKentaurus,                     // "RigelKentaurus"
    AStr_Procyon,                            // "Procyon"
    AStr_Betelgeuse,                         // "Betelgeuse"
    AStr_Achernar,                           // "Achernar"
    AStr_Hadar,                              // "Hadar"
    AStr_Altair,                             // "Altair"
    AStr_Acrux,                              // "Acrux"
    AStr_Aldebaran,                          // "Aldebaran"
    AStr_Spica,                              // "Spica"
    AStr_Antares,                            // "Antares"
    AStr_Pollux,                             // "Pollux"
    AStr_Fomalhaut,                          // "Fomalhaut"
    AStr_Deneb,                              // "Deneb"
    AStr_Regulus,                            // "Regulus"
    AStr_Polaris,                            // "Polaris"
    AStr_Castor,                             // "Castor"
    AStr_Bellatrix,                          // "Bellatrix"
    AStr_Alnilam,                            // "Alnilam"
    AStr_Alnitak,                            // "Alnitak"
    AStr_Mizar,                              // "Mizar"
    AStr_Dubhe,                              // "Dubhe"
    AStr_MessierPrefix,                      // "M"
    AStr_CustomTargetPrefix,                 // "CustomTarget"

    // Unit strings
    AStr_N1,                                 // "1"
    AStr_deg,                                // "deg"
    AStr_rad,                                // "rad"
    AStr_m,                                  // "m"
    AStr_ft,                                 // "ft"
    AStr_Percent,                            // "%"
    AStr_mPers,                              // "m/s"
    AStr_ftPers,                             // "ft/s"
    AStr_C,                                  // "C"
    AStr_F,                                  // "F"
    AStr_K,                                  // "K"
    AStr_PercentRH,                          // "%RH"
    AStr_W,                                  // "W"
    AStr_V,                                  // "V"
    AStr_A,                                  // "A"

    AStr_Log_HasEnabled,                     // "has enabled"
    AStr_Log_HasDisabled,                    // "has disabled"
    AStr_Key_UpdatesPerSec,                  // "updatesPerSec"
    AStr_Key_DisplayTheme,                   // "displayTheme"
    AStr_Key_JoystickCalib,                  // "joystickCalib"
    AStr_Key_UsingISR,                       // "usingISR"
    AStr_Key_StateStableTimeMs,              // "stateStableTimeMs"

    // Generic family strings ported for controller / UI enum conversion
    AStr_Disabled,                           // "Disabled"
    AStr_Err_InitializationFailure,          // "Initialization failure"
    AStr_AC110V,                             // "AC110V"
    AStr_AC220V,                             // "AC220V"
    AStr_DC48V,                              // "DC48V"
    AStr_DescOrder,                          // "DescOrder"
    AStr_AscOrder,                           // "AscOrder"
    AStr_LCD16x2,                            // "LCD16x2"
    AStr_LCD20x4,                            // "LCD20x4"
    AStr_SSD1305,                            // "SSD1305"
    AStr_SSD1305x32Ada,                      // "SSD1305x32Ada"
    AStr_SSD1305x64Ada,                      // "SSD1305x64Ada"
    AStr_SSD1306,                            // "SSD1306"
    AStr_SH1106,                             // "SH1106"
    AStr_CustomOLED,                         // "CustomOLED"
    AStr_SSD1607,                            // "SSD1607"
    AStr_IL3820,                             // "IL3820"
    AStr_IL3820V2,                           // "IL3820V2"
    AStr_ST7735,                             // "ST7735"
    AStr_ST7789,                             // "ST7789"
    AStr_ILI9341,                            // "ILI9341"
    AStr_RotaryEncoder,                      // "RotaryEncoder"
    AStr_UpDownButtons,                      // "UpDownButtons"
    AStr_UpDownESP32Touch,                   // "UpDownESP32Touch"
    AStr_AnalogJoystick,                     // "AnalogJoystick"
    AStr_Matrix2x2,                          // "Matrix2x2"
    AStr_Matrix3x4,                          // "Matrix3x4"
    AStr_Matrix4x4,                          // "Matrix4x4"
    AStr_ResistiveTouch,                     // "ResistiveTouch"
    AStr_TouchScreen,                        // "TouchScreen"
    AStr_TFTTouch,                           // "TFTTouch"
    AStr_RemoteControl,                      // "RemoteControl"

    AStr_Count                               // String count
};

// Blank string pointer used when no Flash string is available.
extern const char *AStr_Blank;

// Returns memory resident string from PROGMEM (Flash), EEPROM, or SD-backed string number.
extern AstroString stringFromPGM(Astro_String strNum);
#define SFP(strNum) stringFromPGM((strNum))

// Returns memory resident string from a PROGMEM (Flash) string address.
extern AstroString stringFromPGMAddr(const char *flashStr);

// Makes string lookup go through EEPROM at the specified data begin address.
extern void beginStringsFromEEPROM(uint16_t dataAddress);

// Makes string lookup go through an SD card strings file at the specified file prefix.
extern void beginStringsFromSDCard(const AstroString &dataFilePrefix);

#ifndef ASTRO_DISABLE_BUILTIN_DATA
// Returns the PROGMEM (Flash) address pointer for a library string.
extern const char *pgmAddrForStr(Astro_String strNum);
#define CFP(strNum) pgmAddrForStr((strNum))
#else
#define CFP(strNum) SFP(strNum).c_str()
#endif

#endif // /ifndef AstroStrings_H
